/// Flutter icons PlacesIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlacesIcons
///      fonts:
///       - asset: fonts/PlacesIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PlacesIcons {
  PlacesIcons._();

  static const _kFontFam = 'PlacesIcons';
  static const String? _kFontPkg = null;

  static const IconData bucket = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_full = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fail = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_full = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_full = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_fill = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData way_arrows_1 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData way_arrows_2 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData way_arrows = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
